### PR TITLE
support for dokku 0.3.x

### PR DESCRIPTION
**Pull request by michaelshobbs**
The bulk of this PR is to make this plugin work with dokku 0.3.x
 specifically in regards to these
- progrium/dokku#884
- progrium/dokku#864

### CODE REVIEW

**Comment by Epigene** [comment]
I approve of this PR.

**Comment by josegonzalez** [comment]
@michaelshobbs doesn't the built-in nginx plugin already support everything in this plugin?

**Comment by michaelshobbs** [comment]
Can't remember right now. I'm using was using this in my deployments prior to the core changes and just want it to work again afterwards. 😁

**Comment by josegonzalez** [comment]
From the readme:
- ~~Multiple custom domains for each app (e.g. myapp.com, www.myapp.com, and production.myapp.com can all be served by the same app). These domains are defined in the VHOST file, with each domain name on a new line.~~ 
  - We handle this now via the domains plugin, no?
- ~~Ability to override nginx.conf. Simply place nginx.tpl or nginx.ssl.tpl files into the app's home directory (i.e. /home/dokku/[app name]/). Upon push, these templates will be used.~~
  - We use nginx.conf.template, but same idea I believe.
- ~~Moved configuration file from post-deploy into separate template files: nginx.conf and nginx.ssl.conf.~~
  - Ditto, this is done.
- ~~Ability to override default .conf files with user's own nginx configuration files placed in /home/dokku/$APP/.~~
  - Yep, just different names.
- ~~Ability to deploy an app under multiple custom domains. The VHOST file can now contain a list of domains that nginx will serve to.~~
  - `dokku domains` handles it exactly like this.
- ~~VHOST file is decoupled from post-deploy in that post-deploy no longer overwrites VHOST after each deploy. Custom domains are set independently in the VHOST file.~~
  - This is still done in `nginx:build-config`, though really we just set it to valid domains (ssl and non-ssl)
- ~~Ability to mix SSL and non-SSL domains. For example, VHOST may contain mydomain.com and *.mydomain.com where SSL certificates only apply to *.mydomain.com. This plugin generates both SSL configurations for the wildcard domains and non-SSL configuration for the root domain.~~
  - Pretty sure you completed this.
- ~~Added helper messages during deploy.~~
  - Samesies, we do this.

Anything else the official plugin is missing? While it would be nice to get this one working, pretty sure it's not necessary anymore.

**Comment by brunowego** [comment]
+1

**Pull request closed without merging**
